### ISSUE TITLE
Update dependency to AFNetworking 2.5

### ISSUE THREAD

**Issue by AnthonyMDev** [JRG-Developer/AFNetworking-ImageActivityIndicator#2]
Because I'm depending on this pod, I'm getting rolled back to `AFNetworking 2.0` when we are now up to `2.5`.

Can we get a new version with the dependent updated pushed to the trunk please? Thanks!

**Comment by JRG-Developer** [comment]
Per the `1.0.0` pod spec,

```
s.dependency 'AFNetworking', '~> 2.0'
```

So, this should _not_ be causing you to depend on an older version of `AFNetworking`.

If I'm missing something here, let me know...?

**Comment by AnthonyMDev** [comment]
The amount of stupidity that I'm feeling right now is immeasurable... _~facepalm~_

I had another pod that was causing the dependency issue I was experiencing.
